### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Club-Manager#3]
## Info

Club members will need a registration page in order to sign up for the club.

This page will use the html template found at `app/clubs/templates/clubs/register-user.html`, and can be found at page <http://localhost:8000/clubs/register/>. You will not need to handle form submission logic, that will be included in another task.

## Task

- [ ] Create basic html template with form for inputting: first name, last name, email, password, confirm password
- [ ] Add some styling to make it not look ugly 
  - styles can be added to a new file in a new `app/clubs/static/clubs/` directory, or can be added to the global `app/static/css/style.css` file - however, if using the former, remember to link it to the html template
  - you can use this tutorial for help: <https://www.w3schools.com/django/django_add_css_file.php/django_add_static_files.php>

_NOTE: Django collects all of the `static` and `templates` folders at compile time and combines them into one directory. This is why the app name (clubs) is repeated inside the static folder above - it helps keep each apps' static files organized after they are combined._

**Comment by sid0000007** [comment]
hey, I read the requirements, I can make it for you. If you can assign it to me,Please do.

**Comment by IkeHunter** [comment]
Cool beans👍

The documentation is still a work in progress, so let me know if you encounter any issues.

**Comment by sid0000007** [comment]
> Cool beans👍
> 
> The documentation is still a work in progress, so let me know if you encounter any issues.

My Docker Compose file is not getting recongised within the terminal. How did you installed docker Compose on mac or linux?

**Comment by IkeHunter** [comment]
@sid0000007 It's been a while since I downloaded it on my mac, but it looks like theres a home brew formula for it: https://formulae.brew.sh/formula/docker-compose, also make sure you have Docker Desktop installed: https://docs.docker.com/desktop/install/mac-install/

**Comment by sid0000007** [comment]
> @sid0000007 It's been a while since I downloaded it on my mac, but it looks like theres a home brew formula for it: https://formulae.brew.sh/formula/docker-compose, also make sure you have Docker Desktop installed: https://docs.docker.com/desktop/install/mac-install/

hello, I have raised a PR for this solution submission. please have a look.
